FPS = 30
WIDTH = 640
HEIGHT = 480
SPACESIZE = 75
FILAS = 6
COLUMNAS = 6
FICHA_B = 'FICHA_B'
FICHA_N = 'FICHA_N'
VACIO = 'VACIO'
AYUDA = 'AYUDA'

ANIMATIONSPEED = 30

Margen_x = int((WIDTH - (FILAS * SPACESIZE)) / 2)
Margen_y = int((HEIGHT - (COLUMNAS * SPACESIZE)) / 2)

#RGB
ROJO = ( 200, 0 , 0)
BLANCO = ( 175 , 175 , 175)
NEGRO = (  0 ,   0 , 0)
VERDE = (  0 , 155 , 0)
GRIS = (50 , 50 , 50)

TXT1 = GRIS
TXT2 = VERDE
LINEAS = NEGRO
COLOR_FUENTE = BLANCO
COLOR_AYUDA = VERDE